# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'banana_inspector/BananaMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.console_2 = Console(self.dockWidgetContents_4)
        self.console_2.setObjectName("console_2")
        self.gridLayout_4.addWidget(self.console_2, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_3)
        self.dockWidget_4 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.banana_plot = BananaPlot(self.dockWidgetContents_5)
        self.banana_plot.setObjectName("banana_plot")
        self.gridLayout_7.addWidget(self.banana_plot, 0, 0, 1, 1)
        self.dockWidget_4.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_4)
        self.basic_controls = QtWidgets.QDockWidget(MainWindow)
        self.basic_controls.setObjectName("basic_controls")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.plot_example = QtWidgets.QPushButton(self.dockWidgetContents_7)
        self.plot_example.setObjectName("plot_example")
        self.gridLayout_6.addWidget(self.plot_example, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.basic_controls.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.basic_controls)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionplot_example = QtWidgets.QAction(MainWindow)
        self.actionplot_example.setObjectName("actionplot_example")
        self.toolBar.addAction(self.actionplot_example)

        self.retranslateUi(MainWindow)
        self.plot_example.clicked.connect(self.banana_plot.plot_example)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plot_example.setText(_translate("MainWindow", "plot example"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionplot_example.setText(_translate("MainWindow", "plot example"))
from .docks.BananaPlot import BananaPlot
from .docks.Console import Console
